CREATE VIEW V_FAT_REMITOS_01
AS

SELECT F2_FILIAL
	,F2_EMISSAO
	,A1_COD
	,A1_LOJA
	,A1_NOME
	,F2_MOEDA
	,F2_TXMOEDA
	,F2_VALBRUT
	,F2_DOC
	,D2_ITEM
	,D2_COD
	,B1_DESC
	,D2_LOTECTL
	,D2_DTVALID
	,D2_QUANT
	,D2_PRCVEN
	,D2_TOTAL
FROM SD2010 SD2
	INNER JOIN SF2010 SF2
		ON D2_FILIAL = F2_FILIAL
		AND D2_CLIENTE = F2_CLIENTE
		AND D2_LOJA = F2_LOJA
		AND D2_DOC = F2_DOC
		AND D2_SERIE = F2_SERIE
		AND D2_ESPECIE = F2_ESPECIE
		AND SF2.D_E_L_E_T_ <> '*'
	INNER JOIN SB1010 SB1
		ON B1_COD = D2_COD
		AND SB1.D_E_L_E_T_ <> '*'
	INNER JOIN SA1010 SA1
		ON A1_COD = D2_CLIENTE
		AND A1_LOJA = D2_LOJA
		AND SA1.D_E_L_E_T_ <> '*'
WHERE D2_ESPECIE = 'RFN'
AND SD2.D_E_L_E_T_ <> '*'

UNION ALL

SELECT F1_FILIAL
	,F1_EMISSAO
	,A1_COD
	,A1_LOJA
	,A1_NOME
	,F1_MOEDA
	,F1_TXMOEDA
	,F1_VALBRUT
	,F1_DOC
	,D1_ITEM
	,D1_COD
	,B1_DESC
	,D1_LOTECTL
	,D1_DTVALID
	,D1_QUANT
	,D1_VUNIT
	,D1_TOTAL
FROM SD1010 SD1
	INNER JOIN SF1010 SF1
		ON D1_FILIAL = F1_FILIAL
		AND D1_FORNECE = F1_FORNECE
		AND D1_LOJA = F1_LOJA
		AND D1_DOC = F1_DOC
		AND D1_SERIE = F1_SERIE
		AND D1_ESPECIE = F1_ESPECIE
		AND SF1.D_E_L_E_T_ <> '*'
	INNER JOIN SB1010 SB1
		ON B1_COD = D1_COD
		AND SB1.D_E_L_E_T_ <> '*'
	INNER JOIN SA1010 SA1
		ON A1_COD = D1_FORNECE
		AND A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ <> '*'
WHERE D1_ESPECIE = 'RFD'
AND SD1.D_E_L_E_T_ <> '*'
