CREATE VIEW V_FAT_PEDREM_01
AS

SELECT	C5_FILIAL
		,C5_EMISSAO
		,C5_NUM
		,C5_MOEDA
		,C5_TXMOEDA
		,C6_ITEM
		,C6_ENTREG
		,A1_COD
		,A1_LOJA
		,A1_NOME
		,C6_LOCAL
		,C6_PRODUTO
		,B1_DESC
		,'' AS C6_DESC2
		,C6_QTDVEN
		,C6_QTDVEN - C6_QTDENT AS C6_PEND
		,C6_PRCVEN
		,C6_VALOR
		,COALESCE(REM.D2_ITEM, '') AS D2_ITEM
		,COALESCE(REM.D2_SERIE, '') AS D2_SERIE
		,COALESCE(REM.D2_DOC, '') AS D2_DOC
		,COALESCE(REM.D2_QUANT, 0) AS D2_QUANT
		,COALESCE(REM.D2_TOTAL, 0) AS D2_TOTAL
FROM SC5010 SC5
	INNER JOIN SC6010 SC6
		ON C5_FILIAL = C6_FILIAL
		AND C5_NUM = C6_NUM
		AND SC6.D_E_L_E_T_ <> '*'
	INNER JOIN SB1010 SB1
		ON B1_COD = C6_PRODUTO
		AND SB1.D_E_L_E_T_ <> '*'
	INNER JOIN SA1010 SA1
		ON A1_COD = C5_CLIENTE
		AND A1_LOJA = C5_LOJACLI
		AND SA1.D_E_L_E_T_ <> '*'
	LEFT JOIN SD2010 REM
		ON D2_FILIAL = C5_FILIAL
		AND D2_CLIENTE = A1_COD
		AND D2_LOJA = A1_LOJA
		AND D2_PEDIDO = C5_NUM
		AND D2_ITEMPV = C6_ITEM
		AND D2_ESPECIE = 'RFN'
		AND REM.D_E_L_E_T_ <> '*'
	--INNER JOIN SD2010 FACT
	--	ON FACT.D2_FILIAL = REM.D2_FILIAL
	--	AND FACT.D2_CLIENTE = REM.D2_CLIENTE
	--	AND FACT.D2_LOJA = REM.D2_LOJA
	--	AND FACT.D2_REMITO = REM.D2_DOC
	--	AND FACT.D2_ITEMREM = REM.D2_ITEM
	--	AND FACT.D2_ESPECIE = 'NF'
	--	AND FACT.D_E_L_E_T_ <> '*'
WHERE SC5.D_E_L_E_T_ <> '*'