DROP VIEW [dbo].[V_FIS_IVA_VENTA_01]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_FIS_IVA_VENTA_01] AS

SELECT	F3_ENTRADA AS [F_Conta], 
		F3_EMISSAO AS [F_Emis], 
		F3_NFISCAL AS [Comprob],	
		Left(F3_SERIE,1) AS [Serie], 
		A1_COD AS [CodCli],
		A1_LOJA AS [LojCli],
		A1_NOME AS [RSocial], 
		A1_CGC AS [CUIT],
		A1_RG AS [DNI],
		F2_PROVENT AS [Prov], 
		A1_TIPO AS [Tipo],
		CASE WHEN F3_ESPECIE = 'NDC' THEN 'ND'
			WHEN F3_ESPECIE = 'NF' THEN 'FAC'
			WHEN F3_ESPECIE = 'NCE' THEN 'NCE'
			ELSE F3_ESPECIE END AS [Tipo_Comp],
		CASE WHEN F3_ESPECIE = 'NDC' THEN 'Nota de Débito'
			WHEN F3_ESPECIE = 'NF' THEN 'Factura'
			WHEN F3_ESPECIE = 'NCE' THEN 'Nota de Cdto. Externa'
			ELSE F3_ESPECIE END AS [Desc_Tipo],
		0 AS [Iva0],
		SUM(F3_VALIMP1) AS [Iva21],  
		SUM(F3_VALIMPY) AS [Iva105],  
		SUM(F3_VALIMPV) AS [Iva27],
		SUM(F3_VALIMPR) AS [Iva2_5],
		0 AS [Iva5],
		SUM(F3_VALIMPQ) AS [Perc_G],  
		SUM(F3_VALIMP9) AS [Perc_IVA],
		SUM(F3_VALIMP2)+
		SUM(F3_VALIMP3)+
		SUM(F3_VALIMP4)+
		SUM(F3_VALIMP5)+
		SUM(F3_VALIMP6)+
		SUM(F3_VALIMP7)+
		SUM(F3_VALIMP8)+
		SUM(F3_VALIMPA)+
		SUM(F3_VALIMPB)+
		SUM(F3_VALIMPC)+
		SUM(F3_VALIMPD)+
		SUM(F3_VALIMPE)+
		SUM(F3_VALIMPF)+
		SUM(F3_VALIMPG)+
		SUM(F3_VALIMPH)+
		SUM(F3_VALIMPI)+
		SUM(F3_VALIMPJ)+
		SUM(F3_VALIMPK)+
		SUM(F3_VALIMPL)+
		SUM(F3_VALIMPM)+
		SUM(F3_VALIMPN)+
		SUM(F3_VALIMPO)+
		SUM(F3_VALIMPP)+
		SUM(F3_VALIMPS) [Perc_IB], 
		0 AS [Perc_Ot], 
		SUM(F3_EXENTAS) AS [Exento], 
		SUM(F3_VALMERC)-SUM(F3_EXENTAS) AS [V_Neto], 
		SUM(F3_VALCONT) AS [V_Bruto]
FROM SF3010 SF3
	INNER JOIN SA1010 SA1
		ON SF3.F3_CLIEFOR = SA1.A1_COD
		AND SF3.F3_LOJA = SA1.A1_LOJA
		AND SA1.D_E_L_E_T_ <> '*'
	INNER JOIN SF2010 SF2
		ON F2_FILIAL = F3_FILIAL
		AND F2_SERIE = F3_SERIE
		AND F2_DOC = F3_NFISCAL
		AND F2_CLIENTE = F3_CLIEFOR
		AND F2_LOJA = F3_LOJA
		AND F2_ESPECIE = F3_ESPECIE
		AND SF2.D_E_L_E_T_ <> '*'
WHERE SF3.D_E_L_E_T_ <> '*' 
AND F3_TIPOMOV = 'V'  
AND F3_ESPECIE IN ('NF','NDC','CF','NCE')
AND F3_DTCANC = ''

GROUP BY F3_REPROC, F3_ENTRADA, F3_EMISSAO, F3_NFISCAL, F3_SERIE, F3_CLIEFOR, F3_LOJA, A1_COD, A1_LOJA, A1_NOME, A1_CGC, A1_RG, 
	A1_EST, A1_TIPO, F3_FORMUL, F3_ESPECIE, F3_PDV, F3_TIPOMOV, F3_FILIAL, F3_DTCANC, F3_TIPO, F2_PROVENT

UNION ALL

SELECT	F3_ENTRADA AS [F_Conta], 
		F3_EMISSAO AS [F_Emis], 
		F3_NFISCAL AS [Comprob], 
		Left(F3_SERIE,1) AS [Serie], 
		A1_COD AS [CodCli],
		A1_LOJA AS [LojCli],
		A1_NOME AS [RSocial], 
		A1_CGC AS [CUIT],
		A1_RG AS [DNI],
		F1_PROVENT AS [Prov], 
		A1_TIPO AS [Tipo],
		'NC' AS [Tipo_Comp],
		'Nota de Crédito' AS [Desc_Tipo],
		0 AS [Iva0],
		SUM(F3_VALIMP1)*-1 AS [Iva21],  
		SUM(F3_VALIMPY)*-1 AS [Iva105],  
		SUM(F3_VALIMPV)*-1 AS [Iva27],
		SUM(F3_VALIMPR)*-1 AS [Iva2_5],
		0 AS [Iva5],
		SUM(F3_VALIMPQ)*-1 AS [Perc_G],  
		SUM(F3_VALIMP9)*-1 AS [Perc_IVA],
		(SUM(F3_VALIMP2)+
		SUM(F3_VALIMP3)+
		SUM(F3_VALIMP4)+
		SUM(F3_VALIMP5)+
		SUM(F3_VALIMP6)+
		SUM(F3_VALIMP7)+
		SUM(F3_VALIMP8)+
		SUM(F3_VALIMPA)+
		SUM(F3_VALIMPB)+
		SUM(F3_VALIMPC)+
		SUM(F3_VALIMPD)+
		SUM(F3_VALIMPE)+
		SUM(F3_VALIMPF)+
		SUM(F3_VALIMPG)+
		SUM(F3_VALIMPH)+
		SUM(F3_VALIMPI)+
		SUM(F3_VALIMPJ)+
		SUM(F3_VALIMPK)+
		SUM(F3_VALIMPL)+
		SUM(F3_VALIMPM)+
		SUM(F3_VALIMPN)+
		SUM(F3_VALIMPO)+
		SUM(F3_VALIMPP)+
		SUM(F3_VALIMPS))*-1 [Perc_IB], 
		0 AS [Perc_Ot], 
		SUM(F3_EXENTAS)*-1 AS [Exento], 
		(SUM(F3_VALMERC)-SUM(F3_EXENTAS))*-1 AS [V_Neto], 
		SUM(F3_VALCONT)*-1 AS [V_Bruto]
FROM SF3010 SF3
	INNER JOIN SA1010 SA1
		ON SF3.F3_CLIEFOR = SA1.A1_COD
		AND SF3.F3_LOJA = SA1.A1_LOJA
		AND SA1.D_E_L_E_T_ <> '*'
	INNER JOIN SF1010 SF1
		ON F1_FILIAL = F3_FILIAL
		AND F1_SERIE = F3_SERIE
		AND F1_DOC = F3_NFISCAL
		AND F1_FORNECE = F3_CLIEFOR
		AND F1_LOJA = F3_LOJA
		AND F1_ESPECIE = F3_ESPECIE
		AND SF1.D_E_L_E_T_ <> '*'
WHERE SF3.D_E_L_E_T_ <> '*' 
AND F3_TIPOMOV = 'V'  
AND F3_ESPECIE IN ('NCC')
AND F3_DTCANC = ''

GROUP BY F3_REPROC, F3_ENTRADA, F3_EMISSAO, F3_NFISCAL, F3_SERIE, F3_CLIEFOR, F3_LOJA, A1_COD, A1_LOJA, A1_NOME, A1_CGC, A1_RG, 
	A1_EST, A1_TIPO, F3_FORMUL, F3_ESPECIE, F3_PDV, F3_TIPOMOV, F3_FILIAL, F3_DTCANC, F3_TIPO, F1_PROVENT
