CREATE VIEW V_FIN_CTACTEPROV_01 
AS

SELECT  'SE2' AS TABLA,
		E2_FILIAL,
        E2_FORNECE,
        E2_LOJA,
        E2_TIPO,
        E2_PREFIXO,
        E2_PARCELA,
		E2_NUM,
        E2_EMISSAO,
        E2_VENCREA,
        E2_NATUREZ,
        E2_MOEDA,
        E2_TXMOEDA,
		E2_VALOR,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 1, E2_TXMOEDA), 0) AS VAL01,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 2, E2_TXMOEDA), 0) AS VAL02,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 3, E2_TXMOEDA), 0) AS VAL03,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 4, E2_TXMOEDA), 0) AS VAL04,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 5, E2_TXMOEDA), 0) AS VAL05,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 1, E2_TXMOEDA), 0) AS SLD01,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 2, E2_TXMOEDA), 0) AS SLD02,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 3, E2_TXMOEDA), 0) AS SLD03,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 4, E2_TXMOEDA), 0) AS SLD04,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 5, E2_TXMOEDA), 0) AS SLD05,
        1 AS SIGNO,
        SE2.R_E_C_N_O_ AS RECTAB
FROM SE2010 SE2
	INNER JOIN SES010 SES
		ON E2_TIPO = ES_TIPO
		AND ES_SINAL = '+'
		AND SES.D_E_L_E_T_ <> '*'
WHERE E2_TIPO <> 'CH'
AND SE2.D_E_L_E_T_ <> '*'

UNION ALL

SELECT  'SE2' AS TABLA,
		E2_FILIAL,
        E2_FORNECE,
        E2_LOJA,
        E2_TIPO,
        E2_PREFIXO,
        E2_PARCELA,
		E2_NUM,
        E2_EMISSAO,
        E2_VENCREA,
        E2_NATUREZ,
        E2_MOEDA,
        E2_TXMOEDA,
		E2_VALOR*-1,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 1, E2_TXMOEDA)*-1, 0) AS VAL01,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 2, E2_TXMOEDA)*-1, 0) AS VAL02,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 3, E2_TXMOEDA)*-1, 0) AS VAL03,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 4, E2_TXMOEDA)*-1, 0) AS VAL04,
        COALESCE(dbo.FN_XVALOR_01(E2_VALOR, E2_EMISSAO, E2_MOEDA, 5, E2_TXMOEDA)*-1, 0) AS VAL05,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 1, E2_TXMOEDA)*-1, 0) AS SLD01,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 2, E2_TXMOEDA)*-1, 0) AS SLD02,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 3, E2_TXMOEDA)*-1, 0) AS SLD03,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 4, E2_TXMOEDA)*-1, 0) AS SLD04,
        COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 5, E2_TXMOEDA)*-1, 0) AS SLD05,
        -1 AS SIGNO,
        SE2.R_E_C_N_O_ AS RECTAB
FROM SE2010 SE2
	INNER JOIN SES010 SES
		ON E2_TIPO = ES_TIPO
		AND ES_SINAL = '-'
		AND SES.D_E_L_E_T_ <> '*'
WHERE E2_TIPO NOT IN ('CH')
AND SE2.D_E_L_E_T_ <> '*'

UNION ALL

SELECT  'SEK',
		EK_FILIAL,
		EK_FORNECE,
		EK_LOJA,
		'OP',
		'ORD',
		'',
		EK_ORDPAGO,
		EK_DTDIGIT,
		EK_DTDIGIT,
		'' AS EK_NATUREZ,
		EK_MOEDA,
		CASE WHEN EK_MOEDA = '1' OR EK_MOEDA = '01' THEN 1 
			WHEN EK_MOEDA = '2' OR EK_MOEDA = '02' THEN EK_TXMOE02
			WHEN EK_MOEDA = '3' OR EK_MOEDA = '03' THEN EK_TXMOE03
			WHEN EK_MOEDA = '4' OR EK_MOEDA = '04' THEN EK_TXMOE04
			WHEN EK_MOEDA = '5' OR EK_MOEDA = '05' THEN EK_TXMOE05 END,
		CASE WHEN EK_TIPO IN ('NCP','PA') THEN 1 ELSE -1 END * SUM(EK_VALOR),
		CASE WHEN EK_TIPO IN ('NCP','PA') THEN 1 ELSE -1 END * SUM(EK_VLMOED1) AS VAL01,
		CASE WHEN EK_TIPO IN ('NCP','PA') THEN 1 ELSE -1 END * COALESCE(SUM(dbo.FN_XVALOR_01(EK_VLMOED1, EK_DTDIGIT, 1, 2, EK_TXMOE02)),0) AS VAL02,
		CASE WHEN EK_TIPO IN ('NCP','PA') THEN 1 ELSE -1 END * COALESCE(SUM(dbo.FN_XVALOR_01(EK_VLMOED1, EK_DTDIGIT, 1, 3, EK_TXMOE03)),0) AS VAL03,
		CASE WHEN EK_TIPO IN ('NCP','PA') THEN 1 ELSE -1 END * COALESCE(SUM(dbo.FN_XVALOR_01(EK_VLMOED1, EK_DTDIGIT, 1, 4, EK_TXMOE04)),0) AS VAL04,
		CASE WHEN EK_TIPO IN ('NCP','PA') THEN 1 ELSE -1 END * COALESCE(SUM(dbo.FN_XVALOR_01(EK_VLMOED1, EK_DTDIGIT, 1, 5, EK_TXMOE05)),0) AS VAL05,
		0 AS SLD01,
		0 AS SLD02,
		0 AS SLD03,
		0 AS SLD04,
		0 AS SLD05,
		CASE WHEN EK_TIPO IN ('NCP','PA') THEN 1 ELSE -1 END AS SIGNO,
		MAX(SEK.R_E_C_N_O_) AS RECTAB
FROM SEK010 SEK
WHERE EK_TIPODOC = 'TB'
AND EK_CANCEL = 'F'
AND SEK.D_E_L_E_T_ <> '*'
GROUP BY EK_FILIAL
	,EK_FORNECE
	,EK_LOJA
	,EK_ORDPAGO
	,EK_DTDIGIT
	,EK_MOEDA
	,EK_TIPO
	,EK_TIPODOC
	,EK_TXMOE02
	,EK_TXMOE03
	,EK_TXMOE04
	,EK_TXMOE05