CREATE VIEW V_FIN_TITPENDCLI_01
AS

SELECT	E1_FILIAL
		,E1_TIPO
		,E1_PARCELA
		,E1_PREFIXO
		,E1_NUM
		,E1_CLIENTE
		,E1_LOJA
		,E1_EMISSAO
		,E1_VENCTO
		,E1_MOEDA
		,E1_TXMOEDA
		,E1_SALDO*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END AS E1_SALDO
        ,COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 1, E1_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD01
        ,COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 2, E1_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD02
        ,COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 3, E1_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD03
        ,COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 4, E1_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD04
        ,COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 5, E1_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD05
		,CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END AS SIGNO
FROM SE1010 SE1
	INNER JOIN SES010 SES
		ON E1_TIPO = ES_TIPO
		AND SES.D_E_L_E_T_ <> '*'
WHERE SE1.D_E_L_E_T_ <> '*'
AND E1_TIPO <> 'CH'
AND E1_SALDO <> 0