ALTER VIEW V_FIN_CTACTECLI_01
AS

SELECT  'SE1' AS TABLA,
		E1_FILIAL,
        E1_CLIENTE,
        E1_LOJA,
        E1_TIPO,
        E1_PREFIXO,
        E1_PARCELA,
		E1_NUM,
        E1_EMISSAO,
        E1_VENCREA,
        E1_NATUREZ,
		'' AS SERAPLI,
		'' AS FACAPLI,		
        E1_MOEDA,
        E1_TXMOEDA,
		E1_VALOR,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 1, E1_TXMOEDA), 0) AS VAL01,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 2, E1_TXMOEDA), 0) AS VAL02,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 3, E1_TXMOEDA), 0) AS VAL03,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 4, E1_TXMOEDA), 0) AS VAL04,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 5, E1_TXMOEDA), 0) AS VAL05,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 1, E1_TXMOEDA), 0) AS SLD01,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 2, E1_TXMOEDA), 0) AS SLD02,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 3, E1_TXMOEDA), 0) AS SLD03,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 4, E1_TXMOEDA), 0) AS SLD04,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 5, E1_TXMOEDA), 0) AS SLD05,
        1 AS SIGNO,
        SE1.R_E_C_N_O_ AS RECTAB
FROM SE1010 SE1
	INNER JOIN SES010 SES
		ON E1_TIPO = ES_TIPO
		AND ES_SINAL = '+'
		AND SES.D_E_L_E_T_ <> '*'
WHERE E1_TIPO <> 'CH'
AND SE1.D_E_L_E_T_ <> '*'

UNION ALL

SELECT  'SE1' AS TABLA,
		E1_FILIAL,
        E1_CLIENTE,
        E1_LOJA,
        E1_TIPO,
        E1_PREFIXO,
        E1_PARCELA,
		E1_NUM,
        E1_EMISSAO,
        E1_VENCREA,
        E1_NATUREZ,
		'' AS SERAPLI,
		'' AS FACAPLI,			
        E1_MOEDA,
        E1_TXMOEDA,
		E1_VALOR*-1,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 1, E1_TXMOEDA)*-1, 0) AS VAL01,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 2, E1_TXMOEDA)*-1, 0) AS VAL02,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 3, E1_TXMOEDA)*-1, 0) AS VAL03,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 4, E1_TXMOEDA)*-1, 0) AS VAL04,
        COALESCE(dbo.FN_XVALOR_01(E1_VALOR, E1_EMISSAO, E1_MOEDA, 5, E1_TXMOEDA)*-1, 0) AS VAL05,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 1, E1_TXMOEDA)*-1, 0) AS SLD01,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 2, E1_TXMOEDA)*-1, 0) AS SLD02,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 3, E1_TXMOEDA)*-1, 0) AS SLD03,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 4, E1_TXMOEDA)*-1, 0) AS SLD04,
        COALESCE(dbo.FN_XVALOR_01(E1_SALDO, E1_EMISSAO, E1_MOEDA, 5, E1_TXMOEDA)*-1, 0) AS SLD05,
        -1 AS SIGNO,
        SE1.R_E_C_N_O_ AS RECTAB
FROM SE1010 SE1
	INNER JOIN SES010 SES
		ON E1_TIPO = ES_TIPO
		AND ES_SINAL = '-'
		AND SES.D_E_L_E_T_ <> '*'
WHERE E1_TIPO NOT IN ('CH')
AND SE1.D_E_L_E_T_ <> '*'

UNION ALL

SELECT  'SEL',
		EL_FILIAL,
		EL_CLIENTE,
		EL_LOJA,
		'RC',
		'REC',
		'',
		EL_RECIBO,
		EL_DTDIGIT,
		EL_DTDIGIT,
		EL_NATUREZ,
		EL_PREFIXO AS SERAPLI,
		EL_NUMERO AS FACAPLI,
		EL_MOEDA,
		CASE WHEN EL_MOEDA = '1' OR EL_MOEDA = '01' THEN 1 
			WHEN EL_MOEDA = '2' OR EL_MOEDA = '02' THEN EL_TXMOE02
			WHEN EL_MOEDA = '3' OR EL_MOEDA = '03' THEN EL_TXMOE03
			WHEN EL_MOEDA = '4' OR EL_MOEDA = '04' THEN EL_TXMOE04
			WHEN EL_MOEDA = '5' OR EL_MOEDA = '05' THEN EL_TXMOE05 END,
		CASE WHEN EL_TIPO IN ('NCC','RA') THEN 1 ELSE -1 END * (EL_VALOR),
		CASE WHEN EL_TIPO IN ('NCC','RA') THEN 1 ELSE -1 END * (EL_VLMOED1) AS VAL01,
		CASE WHEN EL_TIPO IN ('NCC','RA') THEN 1 ELSE -1 END * COALESCE((dbo.FN_XVALOR_01(EL_VLMOED1, EL_DTDIGIT, 1, 2, EL_TXMOE02)),0) AS VAL02,
		CASE WHEN EL_TIPO IN ('NCC','RA') THEN 1 ELSE -1 END * COALESCE((dbo.FN_XVALOR_01(EL_VLMOED1, EL_DTDIGIT, 1, 3, EL_TXMOE03)),0) AS VAL03,
		CASE WHEN EL_TIPO IN ('NCC','RA') THEN 1 ELSE -1 END * COALESCE((dbo.FN_XVALOR_01(EL_VLMOED1, EL_DTDIGIT, 1, 4, EL_TXMOE04)),0) AS VAL04,
		CASE WHEN EL_TIPO IN ('NCC','RA') THEN 1 ELSE -1 END * COALESCE((dbo.FN_XVALOR_01(EL_VLMOED1, EL_DTDIGIT, 1, 5, EL_TXMOE05)),0) AS VAL05,
		0 AS SLD01,
		0 AS SLD02,
		0 AS SLD03,
		0 AS SLD04,
		0 AS SLD05,
		CASE WHEN EL_TIPO IN ('NCC','RA') THEN 1 ELSE -1 END AS SIGNO,
		SEL.R_E_C_N_O_ AS RECTAB
FROM SEL010 SEL
WHERE EL_TIPODOC IN ('TB')
AND EL_CANCEL = 'F'
AND SEL.D_E_L_E_T_ <> '*'


