CREATE VIEW V_FIN_MOVBANCOS_01
AS 

SELECT E5_DTDISPO
	,E5_DATA
	,E5_VENCTO
	,E5_TIPO
	,E5_TIPODOC
	,E5_BANCO
	,E5_AGENCIA
	,E5_CONTA       
	,E5_BENEF
	,E5_HISTOR
	,E5_RECPAG
	,E5_ORDREC
	,E5_CLIFOR
	,E5_LOJA
	,E5_TXMOEDA
	,A6_MOEDA
	,CASE WHEN E5_RECPAG = 'R' THEN 1 ELSE -1 END * E5_VALOR AS E5_VALOR
	,CASE WHEN E5_RECPAG = 'R' THEN 1 ELSE -1 END * COALESCE(dbo.FN_XVALOR_01(E5_VALOR, E5_DATA, A6_MOEDA, 1, E5_TXMOEDA), 0) AS VLRMON01
	,CASE WHEN E5_RECPAG = 'R' THEN 1 ELSE -1 END * COALESCE(dbo.FN_XVALOR_01(E5_VALOR, E5_DATA, A6_MOEDA, 2, E5_TXMOEDA), 0) AS VLRMON02
	,CASE WHEN E5_RECPAG = 'R' THEN 1 ELSE -1 END * COALESCE(dbo.FN_XVALOR_01(E5_VALOR, E5_DATA, A6_MOEDA, 3, E5_TXMOEDA), 0) AS VLRMON03
	,CASE WHEN E5_RECPAG = 'R' THEN 1 ELSE -1 END * COALESCE(dbo.FN_XVALOR_01(E5_VALOR, E5_DATA, A6_MOEDA, 4, E5_TXMOEDA), 0) AS VLRMON04
	,CASE WHEN E5_RECPAG = 'R' THEN 1 ELSE -1 END * COALESCE(dbo.FN_XVALOR_01(E5_VALOR, E5_DATA, A6_MOEDA, 5, E5_TXMOEDA), 0) AS VLRMON05
FROM SE5010 SE5
	INNER JOIN  SA6010 SA6
		ON E5_BANCO = A6_COD
		AND E5_AGENCIA = A6_AGENCIA
		AND E5_CONTA = A6_NUMCON
		AND SA6.D_E_L_E_T_ <> '*'
WHERE E5_VALOR <> 0
AND E5_SITUACA <> 'C'
AND E5_TIPODOC NOT IN ('DC','JR','MT','CM','D2','J2','M2','C2','V2','CP','TL','BA')
AND NOT (E5_MOEDA IN ('C1','C2','C3','C4','C5','CH') AND E5_NUMCHEQ = '               ' AND (E5_TIPODOC NOT IN('TR','TE')))
AND NOT (E5_TIPODOC IN ('TR','TE') AND ((E5_NUMCHEQ BETWEEN '*              ' AND '*ZZZZZZZZZZZZZZ') OR (E5_DOCUMEN BETWEEN '*                ' AND '*ZZZZZZZZZZZZZZZZ' )))
AND NOT (E5_TIPODOC IN ('TR','TE') AND E5_NUMERO = '      ' AND   E5_MOEDA NOT IN ('$','01','CC','CD','CH','CO','DOC','FI','TB','TC','VL','','$ ','DO')  )
AND NOT (E5_NUMCHEQ BETWEEN '*              ' AND '*ZZZZZZZZZZZZZZ')
AND SE5.D_E_L_E_T_ <> '*'
