DROP VIEW [dbo].[V_FIS_IVA_COMPRA_01]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_FIS_IVA_COMPRA_01] AS

SELECT	F3_ENTRADA AS [F_Conta], 
		F3_EMISSAO AS [F_Emis], 
		F3_NFISCAL AS [Comprob], 
		F3_SERIE AS [Serie], 
		A2_COD AS [CodProv],
		A2_LOJA AS [LojProv],
		A2_NOME AS [RSocial], 
		A2_CGC AS [CUIT], 
		F1_PROVENT AS [Prov],
		A2_TIPO AS [Tipo],
		CASE WHEN F3_ESPECIE = 'NDP' THEN 'ND'
			ELSE 'FAC' END AS [Tipo_Comp],
		CASE WHEN F3_ESPECIE = 'NDP' THEN 'Nota de Débito'
			ELSE 'Factura' END AS [Desc_Tipo],
		0 AS [Iva0],
		SUM(F3_VALIMP1) AS [Iva21],  
		SUM(F3_VALIMPY) AS [Iva105],  
		SUM(F3_VALIMPV) AS [Iva27],
		SUM(F3_VALIMPR) AS [Iva2_5],
		0 AS [Iva5],
		SUM(F3_VALIMPQ) AS [Perc_G],  
		SUM(F3_VALIMP9) AS [Perc_IVA],
		SUM(F3_VALIMP2)+
		SUM(F3_VALIMP3)+
		SUM(F3_VALIMP4)+
		SUM(F3_VALIMP5)+
		SUM(F3_VALIMP6)+
		SUM(F3_VALIMP7)+
		SUM(F3_VALIMP8)+
		SUM(F3_VALIMPA)+
		SUM(F3_VALIMPB)+
		SUM(F3_VALIMPC)+
		SUM(F3_VALIMPD)+
		SUM(F3_VALIMPE)+
		SUM(F3_VALIMPF)+
		SUM(F3_VALIMPG)+
		SUM(F3_VALIMPH)+
		SUM(F3_VALIMPI)+
		SUM(F3_VALIMPJ)+
		SUM(F3_VALIMPK)+
		SUM(F3_VALIMPL)+
		SUM(F3_VALIMPM)+
		SUM(F3_VALIMPN)+
		SUM(F3_VALIMPO)+
		SUM(F3_VALIMPP)+
		SUM(F3_VALIMPS) [Perc_IB], 
		0 AS [Perc_Ot], 
		SUM(F3_EXENTAS) AS [Exento], 
		SUM(F3_VALMERC)-SUM(F3_EXENTAS) AS [V_Neto], 
		SUM(F3_VALCONT) AS [V_Bruto]
FROM SF3010 SF3
	INNER JOIN SA2010 SA2
		ON SF3.F3_CLIEFOR = SA2.A2_COD
		AND SF3.F3_LOJA = SA2.A2_LOJA
		AND SA2.D_E_L_E_T_ <> '*'
	INNER JOIN SF1010 SF1
		ON F1_FILIAL = F3_FILIAL
		AND F1_SERIE = F3_SERIE
		AND F1_DOC = F3_NFISCAL
		AND F1_FORNECE = F3_CLIEFOR
		AND F1_LOJA = F3_LOJA
		AND F1_ESPECIE = F3_ESPECIE
		AND SF1.D_E_L_E_T_ <> '*'
WHERE SF3.D_E_L_E_T_ <> '*' 
AND F3_TIPOMOV = 'C'  
AND F3_ESPECIE IN ('NF','NDP')
AND F3_DTCANC = ''

GROUP BY F3_REPROC, F3_ENTRADA, F3_EMISSAO, F3_NFISCAL, F3_SERIE, F3_CLIEFOR, F3_LOJA, A2_NOME, A2_COD, A2_LOJA, A2_CGC,
		A2_EST, A2_TIPO, F3_FORMUL, F3_ESPECIE, F3_PDV, F3_TIPOMOV, F3_FILIAL, F3_DTCANC, F3_TIPO, F1_PROVENT

UNION ALL

SELECT	F3_ENTRADA AS [F_Conta], 
		F3_EMISSAO AS [F_Emis], 
		F3_NFISCAL AS [Comprob], 
		F3_SERIE AS [Serie], 
		A2_COD AS [CodProv],
		A2_LOJA AS [LojProv],
		A2_NOME AS [RSocial], 
		A2_CGC AS [CUIT], 
		F2_PROVENT AS [Prov],
		A2_TIPO AS [Tipo],
		'NC' AS [Tipo_Comp],
		'Nota de Crédito' AS [Desc_Tipo],
		0 AS [Iva0],
		SUM(F3_VALIMP1)*-1 AS [Iva21],  
		SUM(F3_VALIMPY)*-1 AS [Iva105],  
		SUM(F3_VALIMPV)*-1 AS [Iva27],
		SUM(F3_VALIMPR)*-1 AS [Iva2_5],
		0 AS [Iva5],
		SUM(F3_VALIMPQ)*-1 AS [Perc_G],  
		SUM(F3_VALIMP9)*-1 AS [Perc_IVA],
		(SUM(F3_VALIMP2)+
		SUM(F3_VALIMP3)+
		SUM(F3_VALIMP4)+
		SUM(F3_VALIMP5)+
		SUM(F3_VALIMP6)+
		SUM(F3_VALIMP7)+
		SUM(F3_VALIMP8)+
		SUM(F3_VALIMPA)+
		SUM(F3_VALIMPB)+
		SUM(F3_VALIMPC)+
		SUM(F3_VALIMPD)+
		SUM(F3_VALIMPE)+
		SUM(F3_VALIMPF)+
		SUM(F3_VALIMPG)+
		SUM(F3_VALIMPH)+
		SUM(F3_VALIMPI)+
		SUM(F3_VALIMPJ)+
		SUM(F3_VALIMPK)+
		SUM(F3_VALIMPL)+
		SUM(F3_VALIMPM)+
		SUM(F3_VALIMPN)+
		SUM(F3_VALIMPO)+
		SUM(F3_VALIMPP)+
		SUM(F3_VALIMPS))*-1 [Perc_IB], 
		0 AS [Perc_Ot], 
		SUM(F3_EXENTAS)*-1 AS [Exento], 
		(SUM(F3_VALMERC)-SUM(F3_EXENTAS))*-1 AS [V_Neto], 
		SUM(F3_VALCONT)*-1 AS [V_Bruto]
FROM SF3010 SF3
	INNER JOIN SA2010 SA2
		ON SF3.F3_CLIEFOR = SA2.A2_COD
		AND SF3.F3_LOJA = SA2.A2_LOJA
		AND SA2.D_E_L_E_T_ <> '*'
	INNER JOIN SF2010 SF2
		ON F2_FILIAL = F3_FILIAL
		AND F2_SERIE = F3_SERIE
		AND F2_DOC = F3_NFISCAL
		AND F2_CLIENTE = F3_CLIEFOR
		AND F2_LOJA = F3_LOJA
		AND F2_ESPECIE = F3_ESPECIE
		AND SF2.D_E_L_E_T_ <> '*'
WHERE SF3.D_E_L_E_T_ <> '*' 
AND F3_TIPOMOV = 'C'  
AND F3_ESPECIE IN ('NCP')
AND F3_DTCANC = ''

GROUP BY F3_REPROC, F3_ENTRADA, F3_EMISSAO, F3_NFISCAL, F3_SERIE, F3_CLIEFOR, F3_LOJA, A2_NOME, A2_COD, A2_LOJA, A2_CGC,
		A2_EST, A2_TIPO, F3_FORMUL, F3_ESPECIE, F3_PDV, F3_TIPOMOV, F3_FILIAL, F3_DTCANC, F3_TIPO, F2_PROVENT
GO


