CREATE VIEW V_FIN_TITPENDPROV_01
AS

SELECT	E2_FILIAL
		,E2_TIPO
		,E2_PARCELA
		,E2_PREFIXO
		,E2_NUM
		,E2_FORNECE
		,E2_LOJA
		,E2_EMISSAO
		,E2_VENCTO
		,E2_MOEDA
		,E2_TXMOEDA
		,E2_SALDO*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END AS E2_SALDO
        ,COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 1, E2_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD01
        ,COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 2, E2_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD02
        ,COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 3, E2_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD03
        ,COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 4, E2_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD04
        ,COALESCE(dbo.FN_XVALOR_01(E2_SALDO, E2_EMISSAO, E2_MOEDA, 5, E2_TXMOEDA)*CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END, 0) AS SLD05
		,CASE WHEN ES_SINAL = '+' THEN 1 ELSE -1 END AS SIGNO
FROM SE2010 SE2
	INNER JOIN SES010 SES
		ON E2_TIPO = ES_TIPO
		AND SES.D_E_L_E_T_ <> '*'
WHERE SE2.D_E_L_E_T_ <> '*'
AND E2_TIPO <> 'CH'
AND E2_SALDO <> 0
