SELECT RTRIM(Valor)+' => '+RTrim(Contenido) As Documentacion
FROM (
	SELECT CAST(X3_ARQUIVO AS VARCHAR(200)) AS X3_ARQUIVO
	    ,CAST(X3_CAMPO AS VARCHAR(200))	    AS X3_CAMPO
		,CAST(X3_TIPO AS VARCHAR(200))      AS X3_TIPO
		,CAST(X3_TAMANHO AS VARCHAR(200))   AS X3_TAMANHO
		,CAST(X3_DECIMAL AS VARCHAR(200))   AS X3_DECIMAL
		,CAST(X3_PICTURE AS VARCHAR(200))	AS X3_PICTURE
		,CAST(X3_TITSPA AS VARCHAR(200))	AS X3_TITSPA
		,CAST(X3_DESCSPA AS VARCHAR(200))	AS X3_DESCSPA
		,CAST(CASE WHEN SUBSTRING(X3_USADO,113,8)='x       ' THEN 'No' Else 'Si' END AS VARCHAR(200)) AS X3_USADO
		,CAST(CASE WHEN X3_OBRIGAT = '' THEN 'No' ELSE 'Si' END AS VARCHAR(200))	AS X3_OBRIGAT
		,CAST(CASE WHEN X3_BROWSE = 'N' THEN 'No' ELSE 'Si' END AS VARCHAR(200))	AS X3_BROWSE
		,CAST(X3_F3 AS VARCHAR(200))	    AS X3_F3
		,CAST(X3_VALID AS VARCHAR(200))	    AS X3_VALID
		,CAST(X3_VLDUSER AS VARCHAR(200))	AS X3_VLDUSER
		,CAST(X3_CBOXSPA AS VARCHAR(200))	AS X3_CBOXSPA
	FROM SX3010
	-- Filtrar por lo que se desee
	WHERE X3_CAMPO = 'F2_XDTRCPN' 
	) UP
UNPIVOT
	(Contenido FOR Valor IN (X3_ARQUIVO, X3_CAMPO, X3_TIPO, X3_TAMANHO, X3_DECIMAL, X3_PICTURE, X3_TITSPA, X3_DESCSPA, X3_USADO, X3_OBRIGAT, X3_BROWSE, X3_F3, X3_VALID, X3_VLDUSER, X3_CBOXSPA)) AS UNPVT

