
SELECT D1_ITEM
	,D1_COD
	,B1_DESC
	,D1_EMISSAO AS FECHA
	,D1_SERIE
	,D1_DOC
	,D1_QUANT
	,D1_TOTAL
	,F1_MOEDA
	,F1_TXMOEDA AS COTIZACION
	,D1_DTVALID
	,D1_LOTECTL
	,D1_PEDIDO
	,D1_QTDPEDI AS CANT_PED
	,IIF((D1_QTDPEDI - D1_QUANT) = 0, 'Total', IIF((D1_QTDPEDI - D1_QUANT) < 0, '', 'Parcial')) AS ESTADO
	,D1_FORNECE
	,D1_LOJA
	,A2_NOME
	,D1_LOCAL
	,NNR_DESCRI
	,D1_ESPECIE
	,D1_TES
	,S_ORIG = CAST(STUFF(( SELECT DISTINCT '/'+RTRIM(D1_SERIE)
				FROM SD1010 FACT
				WHERE FACT.D1_FILIAL = REMSF1.F1_FILIAL
				AND FACT.D1_FORNECE = REMSF1.F1_FORNECE
				AND FACT.D1_LOJA = REMSF1.F1_LOJA
				AND FACT.D1_SERIREM = REMSF1.F1_SERIE
				AND FACT.D1_REMITO = REMSF1.F1_DOC
				AND FACT.D1_ESPECIE = 'NF'
				AND FACT.D_E_L_E_T_ <> '*'  
				ORDER BY 1
				FOR XML PATH('')), 1, 1, '') AS VARCHAR(100))
	,D_ORIG = CAST(STUFF(( SELECT DISTINCT '/'+RTRIM(D1_DOC)
				FROM SD1010 FACT
				WHERE FACT.D1_FILIAL = REMSF1.F1_FILIAL
				AND FACT.D1_FORNECE = REMSF1.F1_FORNECE
				AND FACT.D1_LOJA = REMSF1.F1_LOJA
				AND FACT.D1_SERIREM = REMSF1.F1_SERIE
				AND FACT.D1_REMITO = REMSF1.F1_DOC
				AND FACT.D1_ESPECIE = 'NF'
				AND FACT.D_E_L_E_T_ <> '*'  
				ORDER BY 1
				FOR XML PATH('')), 1, 1, '') AS VARCHAR(100))
FROM SD1010 REMSD1
	INNER JOIN SB1010 
		ON B1_COD = D1_COD
		AND SB1010.D_E_L_E_T_ <> '*'
	INNER JOIN SF1010 REMSF1
		ON F1_ESPECIE = D1_ESPECIE
		AND F1_SERIE = D1_SERIE
		AND F1_DOC = D1_DOC
		AND F1_FORNECE = D1_FORNECE
		AND F1_LOJA = D1_LOJA
		AND REMSF1.D_E_L_E_T_ <> '*'
	INNER JOIN NNR010 
		ON NNR_CODIGO = D1_LOCAL
		AND NNR010.D_E_L_E_T_ <> '*'
	INNER JOIN SA2010 
		ON A2_COD = D1_FORNECE
		AND A2_LOJA = D1_LOJA
		AND SA2010.D_E_L_E_T_ <> '*'
	INNER JOIN SF4010 SF4
		ON F4_CODIGO = D1_TES
		AND F4_ESTOQUE = 'S'
		AND SF4.D_E_L_E_T_ <> '*'
WHERE D1_ESPECIE IN ('RCN')
AND D1_REMITO = ''
AND REMSD1.D_E_L_E_T_ <> '*'

UNION ALL

SELECT D1_ITEM
	,D1_COD
	,B1_DESC
	,D1_EMISSAO AS FECHA
	,D1_SERIE
	,D1_DOC
	,D1_QUANT
	,D1_TOTAL
	,F1_MOEDA
	,F1_TXMOEDA AS COTIZACION
	,D1_DTVALID
	,D1_LOTECTL
	,D1_PEDIDO
	,D1_QTDPEDI AS CANT_PED
	,IIF((D1_QTDPEDI - D1_QUANT) = 0, 'Total', IIF((D1_QTDPEDI - D1_QUANT) < 0, '', 'Parcial')) AS ESTADO
	,D1_FORNECE
	,D1_LOJA
	,A2_NOME
	,D1_LOCAL
	,NNR_DESCRI
	,D1_ESPECIE
	,D1_TES
	,S_ORIG = CAST(STUFF(( SELECT DISTINCT '/'+D2_SERIE
				FROM SD2010 NCP
				WHERE NCP.D2_FILIAL = SF1.F1_FILIAL
				AND NCP.D2_CLIENTE = SF1.F1_FORNECE
				AND NCP.D2_LOJA = SF1.F1_LOJA
				AND NCP.D2_SERIORI = SF1.F1_SERIE
				AND NCP.D2_NFORI = SF1.F1_DOC
				AND NCP.D2_ESPECIE = 'NCP'
				AND NCP.D_E_L_E_T_ <> '*'  
				ORDER BY 1
				FOR XML PATH('')), 1, 1, '') AS VARCHAR(100))
	,D_ORIG = CAST(STUFF(( SELECT DISTINCT '/'+D2_DOC
				FROM SD2010 NCP
				WHERE NCP.D2_FILIAL = SF1.F1_FILIAL
				AND NCP.D2_CLIENTE = SF1.F1_FORNECE
				AND NCP.D2_LOJA = SF1.F1_LOJA
				AND NCP.D2_SERIORI = SF1.F1_SERIE
				AND NCP.D2_NFORI = SF1.F1_DOC
				AND NCP.D2_ESPECIE = 'NCP'
				AND NCP.D_E_L_E_T_ <> '*'  
				ORDER BY 1
				FOR XML PATH('')), 1, 1, '') AS VARCHAR(100))
FROM SD1010 SD1
	INNER JOIN SB1010 SB1
		ON B1_COD = D1_COD
		AND SB1.D_E_L_E_T_ <> '*'
	INNER JOIN SF1010 SF1
		ON F1_ESPECIE = D1_ESPECIE
		AND F1_SERIE = D1_SERIE
		AND F1_DOC = D1_DOC
		AND F1_FORNECE = D1_FORNECE
		AND F1_LOJA = D1_LOJA
		AND SF1.D_E_L_E_T_ <> '*'
	INNER JOIN NNR010 NNR
		ON NNR_CODIGO = SD1.D1_LOCAL
		AND NNR.D_E_L_E_T_ <> '*'
	INNER JOIN SA2010 SA2
		ON A2_COD = D1_FORNECE
		AND A2_LOJA = D1_LOJA
		AND SA2.D_E_L_E_T_ <> '*'
	INNER JOIN SF4010 SF4
		ON F4_CODIGO = D1_TES
		AND F4_ESTOQUE = 'S'
		AND SF4.D_E_L_E_T_ <> '*'
WHERE D1_ESPECIE IN ('NF')
AND D1_REMITO = ''
AND SD1.D_E_L_E_T_ <> '*'
--AND D1_FORNECE BETWEEN '[p(1)]' AND '[p(2)]'
--AND D1_EMISSAO BETWEEN '[p(3)]' AND '[p(4)]'

UNION ALL

SELECT D2_ITEM
	,D2_COD
	,B1_DESC
	,D2_EMISSAO AS FECHA
	,D2_SERIE
	,D2_DOC
	,D2_QUANT * - 1
	,D2_TOTAL
	,F2_MOEDA
	,F2_TXMOEDA AS COTIZACION
	,D2_DTVALID
	,D2_LOTECTL
	,D2_PEDIDO
	,CANT_PED = ''
	,ESTADO = ''
	,D2_CLIENTE
	,D2_LOJA
	,A2_NOME
	,D2_LOCAL
	,NNR_DESCRI
	,D2_ESPECIE
	,D2_TES
	,D2_SERIORI AS S_ASOC
	,D2_NFORI AS D_ORIG
FROM SD2010 SD2
	INNER JOIN SB1010 SB1
		ON B1_COD = D2_COD
		AND SB1.D_E_L_E_T_ <> '*'
	INNER JOIN SF2010 SF2
		ON F2_ESPECIE = D2_ESPECIE
		AND F2_SERIE = D2_SERIE
		AND F2_DOC = D2_DOC
		AND F2_CLIENTE = D2_CLIENTE
		AND F2_LOJA = D2_LOJA
		AND SF2.D_E_L_E_T_ <> '*'
	INNER JOIN NNR010 NNR
		ON NNR_CODIGO = D2_LOCAL
		AND NNR.D_E_L_E_T_ <> '*'
	INNER JOIN SA2010 SA2
		ON A2_COD = D2_CLIENTE	
		AND A2_LOJA = D2_LOJA
		AND SA2.D_E_L_E_T_ <> '*'
	INNER JOIN SF4010 SF4
		ON F4_CODIGO = D2_TES
		AND F4_ESTOQUE = 'S'
		AND SF4.D_E_L_E_T_ <> '*'
WHERE D2_ESPECIE IN ('NCP', 'RCD')
AND D2_REMITO = ''
AND SD2.D_E_L_E_T_ <> '*'
--AND D2_CLIENTE BETWEEN '[p(1)]' AND '[p(2)]'
--AND D2_EMISSAO BETWEEN '[p(3)]' AND '[p(4)]'