SELECT	B.M_NAME AS COD_MODULO
		,I_ORDER AS ORDEN
		,I_TP_MENU AS COD_TIPOMENU
		,CASE WHEN I_TP_MENU = '1' THEN 'Carpeta' ELSE 'Item' END AS DES_TIPOMENU
		,ISNULL(C.N_DESC,'') AS DES_PADRE
		,ISNULL(E.N_DESC,'') AS DES_ITEM
		,I_ID_FUNC AS ID_FUNCION
		,ISNULL(D.F_FUNCTION,'') AS COD_FUNCION
		,I_STATUS
		,I_RESNAME
		,I_TYPE
		,I_TABLES
		,I_ACCESS
		,I_OWNER
		,I_MODULE
		,I_DEFAULT
FROM MPMENU_ITEM A
	INNER JOIN MPMENU_MENU B
		ON A.I_ID_MENU = B.M_ID
	LEFT JOIN MPMENU_I18N C
		ON A.I_FATHER = C.N_PAREN_ID
		AND C.N_LANG = '2'
	LEFT JOIN MPMENU_FUNCTION D
		ON A.I_ID_FUNC = D.F_ID
	LEFT JOIN MPMENU_I18N E
		ON A.I_ID = E.N_PAREN_ID
		AND E.N_LANG = '2'
WHERE 1=1
--AND B.M_NAME = 'SIGAFIN'
AND ISNULL(D.F_FUNCTION,'') LIKE '%CBU%'
AND B.M_NAME NOT LIKE '#BKP_%'
ORDER BY I_ORDER
