
-- Ejemplo simple que trae tipo de cobro por TF, CH, EF usando
-- PIVOT
SELECT EL_RECIBO, EL_SERIE, EL_DTDIGIT, EL_CLIORIG, EL_LOJORIG
	,SUM(TF) AS TF
	,SUM(CH) AS CH
	,SUM(EF) AS EF
FROM SEL010
PIVOT (SUM(EL_VALOR) FOR EL_TIPODOC IN ([TF],[CH],[EF])) AS PVT
WHERE D_E_L_E_T_ <> '*'
GROUP BY EL_RECIBO, EL_SERIE, EL_DTDIGIT, EL_CLIORIG, EL_LOJORIG
ORDER BY 1,2

-- Mismo ejemplo sin usar pivot
SELECT EL_RECIBO, EL_SERIE, EL_DTDIGIT, EL_CLIORIG, EL_LOJORIG
	,SUM(CASE WHEN EL_TIPODOC = 'TF' THEN EL_VALOR ELSE 0 END) AS TF
	,SUM(CASE WHEN EL_TIPODOC = 'CH' THEN EL_VALOR ELSE 0 END) AS CH
	,SUM(CASE WHEN EL_TIPODOC = 'EF' THEN EL_VALOR ELSE 0 END) AS EF
FROM SEL010
WHERE D_E_L_E_T_ <> '*'
GROUP BY EL_RECIBO, EL_SERIE, EL_DTDIGIT, EL_CLIORIG, EL_LOJORIG
ORDER BY 1,2



