SELECT F2_DOC,
	F2_SERIE,
	F2_CLIENTE,
	F2_LOJA,
	F2_EMISSAO,
	REM.D2_ITEM,
	REM.D2_COD,
	REM.D2_QUANT,
	REM.D2_PRCVEN,
	REM.D2_TOTAL,
	REM.D2_REMITO,
	REM.D2_SERIREM,
	FACT.*
FROM SD2010 REM
	INNER JOIN SF2010 SF2
		ON D2_FILIAL = F2_FILIAL
		AND D2_DOC = F2_DOC
		AND D2_SERIE = F2_SERIE
		AND D2_ESPECIE = F2_ESPECIE
		AND D2_CLIENTE = F2_CLIENTE
		AND D2_LOJA = F2_LOJA
		AND SF2.D_E_L_E_T_ <> '*'
	LEFT JOIN SD2010 FACT
		ON REM.D2_FILIAL = FACT.D2_FILIAL
		AND REM.D2_SERIE = FACT.D2_SERIREM
		AND REM.D2_DOC = FACT.D2_REMITO
		AND REM.D2_ITEM = FACT.D2_ITEM
		AND REM.D2_CLIENTE = FACT.D2_CLIENTE
		AND REM.D2_LOJA = FACT.D2_LOJA
		AND REM.D_E_L_E_T_ <> '*'
WHERE REM.D_E_L_E_T_ <> '*'
AND REM.D2_ESPECIE IN ('RFN')
AND FACT.D2_FILIAL IS NULL
