SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[ACT_BAIXA_SE1] ON [dbo].[SE1010] AFTER INSERT, UPDATE, DELETE
AS 

DECLARE @RECNO INT = (SELECT R_E_C_N_O_ FROM inserted)

IF UPDATE(D_E_L_E_T_)
	BEGIN

	UPDATE SE1010
	SET E1_BAIXA = CONVERT(VARCHAR(8), GETDATE(), 112)
	WHERE R_E_C_N_O_ = @RECNO
	AND D_E_L_E_T_ = '*'
		
	END	

GO


