SELECT	F3_FILIAL
		,FB_CODIGO
		,FB_DESCR
		,FB_ESTADO
		,FB_CLASSE
		,F3_ENTRADA
		,F3_CLIEFOR
		,F3_LOJA
		,F3_ESPECIE
		,F3_NFISCAL
		,F3_SERIE
		,F3_CFO
		,F3_TIPOMOV
		,SUM(CASE WHEN CAMPO LIKE 'F3_BASIMP%' THEN VALOR ELSE 0 END) AS BASIMP
		,MAX(CASE WHEN CAMPO LIKE 'F3_ALQIMP%' THEN VALOR ELSE 0 END) AS ALQIMP
		,SUM(CASE WHEN CAMPO LIKE 'F3_VALIMP%' THEN VALOR ELSE 0 END) AS VALIMP
FROM SF3010 SF3
UNPIVOT (VALOR FOR CAMPO IN (
	F3_VALIMP1,F3_VALIMP2,F3_VALIMP3,F3_VALIMP4,F3_VALIMP5,
	F3_VALIMP6,F3_VALIMP7,F3_VALIMP8,F3_VALIMP9,F3_VALIMPA,
	F3_VALIMPB,F3_VALIMPC,F3_VALIMPD,F3_VALIMPE,F3_VALIMPF,
	F3_VALIMPG,F3_VALIMPH,F3_VALIMPI,F3_VALIMPJ,F3_VALIMPK,
	F3_VALIMPL,F3_VALIMPM,F3_VALIMPN,F3_VALIMPO,F3_VALIMPP,
	F3_VALIMPQ,F3_VALIMPR,F3_VALIMPS,F3_VALIMPT,F3_VALIMPU,
	F3_VALIMPV,F3_VALIMPW,F3_VALIMPX,F3_VALIMPY,F3_VALIMPZ,

	F3_ALQIMP1,F3_ALQIMP2,F3_ALQIMP3,F3_ALQIMP4,F3_ALQIMP5,
	F3_ALQIMP6,F3_ALQIMP7,F3_ALQIMP8,F3_ALQIMP9,F3_ALQIMPA,
	F3_ALQIMPB,F3_ALQIMPC,F3_ALQIMPD,F3_ALQIMPE,F3_ALQIMPF,
	F3_ALQIMPG,F3_ALQIMPH,F3_ALQIMPI,F3_ALQIMPJ,F3_ALQIMPK,
	F3_ALQIMPL,F3_ALQIMPM,F3_ALQIMPN,F3_ALQIMPO,F3_ALQIMPP,
	F3_ALQIMPQ,F3_ALQIMPR,F3_ALQIMPS,F3_ALQIMPT,F3_ALQIMPU,
	F3_ALQIMPV,F3_ALQIMPW,F3_ALQIMPX,F3_ALQIMPY,F3_ALQIMPZ,

	F3_BASIMP1,F3_BASIMP2,F3_BASIMP3,F3_BASIMP4,F3_BASIMP5,
	F3_BASIMP6,F3_BASIMP7,F3_BASIMP8,F3_BASIMP9,F3_BASIMPA,
	F3_BASIMPB,F3_BASIMPC,F3_BASIMPD,F3_BASIMPE,F3_BASIMPF,
	F3_BASIMPG,F3_BASIMPH,F3_BASIMPI,F3_BASIMPJ,F3_BASIMPK,
	F3_BASIMPL,F3_BASIMPM,F3_BASIMPN,F3_BASIMPO,F3_BASIMPP,
	F3_BASIMPQ,F3_BASIMPR,F3_BASIMPS,F3_BASIMPT,F3_BASIMPU,
	F3_BASIMPV,F3_BASIMPW,F3_BASIMPX,F3_BASIMPY,F3_BASIMPZ) ) AS UNPVT
		INNER JOIN SFB010 SFB
			ON RIGHT(CAMPO,1) = FB_CPOLVRO
			AND LEFT(FB_CODIGO,1) <> 'E'
			AND FB_CODIGO NOT IN ('IVC','LVA','IVD')
			AND FB_CLASSE IN ('I','P')
			AND SFB.D_E_L_E_T_ <> '*'
WHERE F3_DTCANC = ' '
AND VALOR <> 0
GROUP BY F3_FILIAL
		,FB_CODIGO
		,FB_DESCR
		,FB_ESTADO
		,FB_CLASSE
		,F3_CLIEFOR
		,F3_LOJA
		,F3_ESPECIE
		,F3_ENTRADA
		,F3_EMISSAO
		,F3_NFISCAL
		,F3_SERIE
		,F3_CFO
		,F3_TIPOMOV
HAVING SUM(CASE WHEN CAMPO LIKE 'F3_VALIMP%' THEN VALOR ELSE 0 END) <> 0
ORDER BY F3_ENTRADA, F3_CLIEFOR, F3_LOJA

